### ISSUE TITLE
Documentation of the library functions

### ISSUE THREAD

**Issue by PTS93** [adafruit/Adafruit_FreeTouch#10]
I tried to sift through the [QTouch user guide](http://ww1.microchip.com/downloads/en/DeviceDoc/QTouch-Modular-Library-Peripheral-Touch-Controller-40001986B.pdf) in order to understand some of the things at play in the PTC but I'm not really smarter than before.
What I'm mostly interested in is what these functions are doing, the concept behind them and how they are practically used.
For example what is a compensation capacitor, what do I do with that and how? Some insight especially for the functions below would be much appericated!
```
  void setSeriesResistor(series_resistor_t res);
  void setFreqHopping(freq_mode_t fh, freq_hop_t hops = FREQ_HOP_1);
  void setCompCap(uint16_t cc);
  void setIntCap(uint8_t ic);
```

**Comment by ladyada** [comment]
since we reverse engineered it from the qtouch library
https://www.mouser.com/pdfdocs/SAMA5D2_PTC_Firmware_UG.pdf
and similar PDF's are going to have the most details! microchip app engineers/support will also be most helpful, we don't have any insight into the low-level functionality (and they're not super forthcoming either :)

**Comment by PTS93** [comment]
Thanks a lot, that document is super helpful!
I wasn't super interested in the low level, I was just confused what the heck these things mean at all :)
